# ==========================================================
# Parallel Admin Tool
# Конфигурация
# ==========================================================

[mysql]

user = koshkin
password = FKFMhzEBPZA7

connect_timeout = 5
read_timeout = 60
write_timeout = 60

retry = 3

[parallel]

workers = 8
database_workers = 4

[filter]

country = russia
country_setting = csSystemCountry
target_setting = banEmailDomain
target_value = gmail.com, icloud.com, hotmail.com, outlook.com, yahoo.com, mail.com, proton.me, aol.com, gmx.com, zoho.com

[logging]

directory = logs
csv = result.csv
errors = errors.log
run = run.log
verbose = true

[output]

color = true
progress = true
eta = true
speed = true
summary = true

[advanced]

ignore = tuple(
    x.strip()
    for x in p.get(
        "advanced",
        "ignore_databases"
    ).replace("\n", "").split(",")
    if x.strip()
)

settings_table = cfg_settings
batch_size = 100
export_csv = true
export_errors = true
